CREATE TABLE songs (
	id serial primary key,
	rank integer,
	artist varchar(80),
	track varchar(120),
	published date
);

-- Leave the id off, so it is auto-generated by the DB
INSERT INTO songs (artist, track, published, rank)
VALUES ('Billy Joel', 'We Didn''t Start the Fire', '1/1/1989', 35);


INSERT INTO songs (artist, track, published, rank)
VALUES ('Toto', 'Africa', '10/30/1982', 42);